[package]
name = "moto-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config = "1.1.8"
aws-sdk-s3 = "1.20.0"
tokio = { version = "1.36.0", features = ["full"] }
